"""Curated stock name -> NSE ticker map, shared by the price and
fundamentals refresh jobs (Yahoo appends \".NS\"; Screener.in uses the bare
symbol). Kept in one place so the two jobs can never drift apart.
"""

TICKERS = {
    "Reliance Industries": "RELIANCE", "Bharti Airtel": "BHARTIARTL", "HDFC Bank": "HDFCBANK",
    "SBI": "SBIN", "ICICI Bank": "ICICIBANK", "TCS": "TCS", "Bajaj Finance": "BAJFINANCE",
    "Larsen & Toubro": "LT", "Hind. Unilever": "HINDUNILVR", "Infosys": "INFY",
    "Sun Pharma": "SUNPHARMA", "Maruti Suzuki": "MARUTI", "Titan Company": "TITAN",
    "M & M": "M&M", "Adani Enterprises": "ADANIENT", "Adani Ports": "ADANIPORTS",
    "Kotak Mah. Bank": "KOTAKBANK", "Axis Bank": "AXISBANK", "HCL Technologies": "HCLTECH",
    "ITC": "ITC", "UltraTech Cement": "ULTRACEMCO", "NTPC": "NTPC",
    "Bajaj Auto": "BAJAJ-AUTO", "Bajaj Finserv": "BAJAJFINSV", "JSW Steel": "JSWSTEEL",
    "Nestle India": "NESTLEIND", "Eternal (Zomato)": "ETERNAL", "ONGC": "ONGC",
    "Bharat Electronics": "BEL", "Asian Paints": "ASIANPAINT", "Shriram Finance": "SHRIRAMFIN",
    "Coal India": "COALINDIA", "Power Grid Corpn": "POWERGRID", "Hindalco Inds": "HINDALCO",
    "Tata Steel": "TATASTEEL", "Grasim Inds": "GRASIM", "Eicher Motors": "EICHERMOT",
    "InterGlobe (IndiGo)": "INDIGO", "Wipro": "WIPRO", "SBI Life Insurance": "SBILIFE",
    "Jio Financial": "JIOFIN", "Tech Mahindra": "TECHM", "Trent": "TRENT",
    "Apollo Hospitals": "APOLLOHOSP", "Tata Motors PV": "TMPV", "Cipla": "CIPLA",
    "HDFC Life Insurance": "HDFCLIFE", "Tata Consumer": "TATACONSUM", "Max Healthcare": "MAXHEALTH",
    "Dr Reddy's Labs": "DRREDDY", "BSE": "BSE", "BHEL": "BHEL", "Polycab India": "POLYCAB",
    "GMR Airports": "GMRAIRPORT", "Hero Motocorp": "HEROMOTOCO", "Marico": "MARICO",
    "Lupin": "LUPIN", "Bharat Forge": "BHARATFORG", "Ashok Leyland": "ASHOKLEY",
    "Indus Towers": "INDUSTOWER", "Mankind Pharma": "MANKIND", "Laurus Labs": "LAURUSLABS",
    "Aurobindo Pharma": "AUROPHARMA", "FSN E-Comm (Nykaa)": "NYKAA", "One97 (Paytm)": "PAYTM",
    "Federal Bank": "FEDERALBNK", "Dixon Technologies": "DIXON", "Persistent Systems": "PERSISTENT",
    "HPCL": "HINDPETRO", "ICICI Lombard": "ICICIGI", "Havells India": "HAVELLS",
    "IndusInd Bank": "INDUSINDBK", "Info Edge (Naukri)": "NAUKRI", "AU Small Finance": "AUBANK",
    "Coforge": "COFORGE", "Swiggy": "SWIGGY", "SRF": "SRF", "Waaree Energies": "WAAREEENER",
    "NHPC": "NHPC", "NMDC": "NMDC", "PB Fintech": "POLICYBZR", "IDFC First Bank": "IDFCFIRSTB",
    "Dabur India": "DABUR", "Oil India": "OIL", "Fortis Healthcare": "FORTIS",
    "Yes Bank": "YESBANK", "Prestige Estates": "PRESTIGE", "Phoenix Mills": "PHOENIXLTD",
    "MCX": "MCX", "Alkem Lab": "ALKEM", "Suzlon Energy": "SUZLON", "SBI Cards": "SBICARD",
    "Godrej Properties": "GODREJPROP", "Colgate-Palmolive": "COLPAL", "APL Apollo Tubes": "APLAPOLLO",
    "Tube Investments": "TIINDIA", "Max Financial": "MFSL", "UPL": "UPL", "Mphasis": "MPHASIS",
    "Supreme Inds": "SUPREMEIND", "Aster DM Healthcare": "ASTERDM", "RBL Bank": "RBLBANK",
    "Hindustan Copper": "HINDCOPPER", "Sona BLW Precision": "SONACOMS", "Welspun Corp": "WELCORP",
    "Aegis Logistics": "AEGISLOG", "Piramal Finance": "PIRAMALFIN", "Gland Pharma": "GLAND",
    "Navin Fluorine Intl": "NAVINFLUOR", "Poonawalla Fincorp": "POONAWALLA",
    "Narayana Hrudayalaya": "NH", "Himadri Speciality": "HSCL", "Tata Technologies": "TATATECH",
    "Delhivery": "DELHIVERY", "Anand Rathi Wealth": "ANANDRATHI", "Manappuram Finance": "MANAPPURAM",
    "Wockhardt": "WOCKPHARMA", "Karur Vysya Bank": "KARURVYSYA", "Dr Lal Pathlabs": "LALPATHLAB",
    "Chola Financial Hldgs": "CHOLAHLDNG", "PNB Housing": "PNBHOUSING", "Neuland Labs": "NEULANDLAB",
    "Sai Life Sciences": "SAILIFE", "Bandhan Bank": "BANDHANBNK", "Piramal Pharma": "PPLPHARMA",
    "Redington": "REDINGTON", "CDSL": "CDSL", "Angel One": "ANGELONE", "Amber Enterprises": "AMBER",
    "IIFL Finance": "IIFL", "Kaynes Technology": "KAYNES", "NBCC": "NBCC", "Affle 3i": "AFFLE",
    "CESC": "CESC", "Indraprastha Gas": "IGL", "City Union Bank": "CUB", "CAMS": "CAMS",
    "Castrol India": "CASTROLIND", "PG Electroplast": "PGEL", "Tata Chemicals": "TATACHEM",
    "Amara Raja Energy": "ARE&M", "Cohance Lifesciences": "COHANCE", "Natco Pharma": "NATCOPHARM",
    "Syngene Intl": "SYNGENE", "Crompton Gr. Consumer": "CROMPTON", "KFin Technologies": "KFINTECH",
    "Five-Star Business Fin": "FIVESTAR", "Inox Wind": "INOXWIND", "KEC International": "KEC",
    "Reliance Power": "RPOWER",
}


